### ISSUE TITLE
REPORTE ENTREVISTA

### ISSUE THREAD

**Issue by Kim-Mendoza3** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equipo-jka#1]
https://drive.google.com/file/d/1H5V9gM5vQvX0EZhZQRNhUJy_FKD1GDNs/view?usp=sharing

**Comment by josealfredo79** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:22/25
Resultados y conclusiones:20/25
Total: 92/100 Calificacion es igual a 27%
